version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "yamap55"
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "daily"
    reviewers:
      - "yamap55"
